name: wifi_info
description: A simple app that measures WiFi communication strength

publish_to: 'none'
version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_riverpod: ^1.0.0
  wifi_iot: ^0.3.8
  charts_flutter: ^0.12.0
  app_review: ^2.1.1+1
  google_mobile_ads: ^0.13.2
  intl: ^0.17.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#2196F3"
  image: "assets/icon/wifi_info_logo.png"

flutter_icons:
  android: true
  image_path: "assets/icon/wifi_info_logo.png"